// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using PropertyChanged;
using Xamarin.Forms;

namespace dalexFDA
{
    [AddINotifyPropertyChangedInterface]
    public partial class LoginViewModel
    {
        //default services
        internal readonly dalexFDA.Abstractions.IErrorManager ErrorManager;

        //other services
        internal readonly dalexFDA.Abstractions.IAppService AppService;

        //commands
        public Command Login { get; private set; }
        public Command Back { get; private set; }
        public Command SignUpExistingUser { get; private set; }
        public Command SignUpNewUser { get; private set; }

        //properties
        public string AccountNumber { get; set; }
        public string Password { get; set; }

        public LoginViewModel
        (
           dalexFDA.Abstractions.IErrorManager ErrorManager
          ,dalexFDA.Abstractions.IAppService AppService
        )
        {
            //setup default services
            this.ErrorManager = ErrorManager;

            //setup other services
            this.AppService = AppService;

            //setup commands
            Login = new Command(async () => await ExecuteLogin());
            Back = new Command(async () => await ExecuteBack());
            SignUpExistingUser = new Command(async () => await ExecuteSignUpExistingUser());
            SignUpNewUser = new Command(async () => await ExecuteSignUpNewUser());
  
            Setup();
        }

 

    }
}
