// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using PropertyChanged;
using Xamarin.Forms;

namespace Zenith
{
    [AddINotifyPropertyChangedInterface]
    public partial class ActivateAccountViewModel
    {
        //default services
        internal readonly Zenith.Abstractions.IErrorManager ErrorManager;

        //other services

        //commands
        public Command Activate { get; private set; }
        public Command Back { get; private set; }
        public Command Swipe { get; private set; }

        //properties
        public string AccountNumber { get; set; }
        public string BVN { get; set; }

        public ActivateAccountViewModel
        (
           Zenith.Abstractions.IErrorManager ErrorManager
        )
        {
            //setup default services
            this.ErrorManager = ErrorManager;

            //setup other services

            //setup commands
            Activate = new Command(async () => await ExecuteActivate());
            Back = new Command(async () => await ExecuteBack());
            Swipe = new Command(async () => await ExecuteSwipe());
  
            Setup();
        }

 

    }
}
