// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using PropertyChanged;
using Xamarin.Forms;

namespace Zenith
{
    [AddINotifyPropertyChangedInterface]
    public partial class ComingSoonViewModel
    {
        //default services
        internal readonly Zenith.Abstractions.IErrorManager ErrorManager;

        //other services

        //commands

        //properties

        public ComingSoonViewModel
        (
           Zenith.Abstractions.IErrorManager ErrorManager
        )
        {
            //setup default services
            this.ErrorManager = ErrorManager;

            //setup other services

            //setup commands
  
            Setup();
        }

 

    }
}
